aws_region: eu-central-1
aws_zone_id: "{{ lookup('env', 'AWS_HOSTED_ZONE_ID') }}"
skynet_worker_deploy_prefetch_images: true

skynet_worker_deploy_services:
  - name: blahblah_dialog
    docker:
      image: 656397365169.dkr.ecr.eu-central-1.amazonaws.com/luka/blahblah_dialog
      tag: "{{ tag | default('latest') }}"
    port: 8090
    state: present
    env:
      ENVIRONMENT: production
      NVIDIA_VISIBLE_DEVICES: all

skynet_balancer_deploy_services:
  - name: blahblah_dialog
    tag: "{{ tag | default('latest') }}"
    port: 8090
    prefixes:
      - prefix: dialog
        sticky_session: true
